### ISSUE TITLE
The experience of using `-m` could be improved

### ISSUE THREAD

**Issue by matroscoe** [brandtbucher/specialist#4]
Amazing tool! The documentation is good but it was a bit confusing when it came to integration with pytest. I would run the following: 

``` shell
specialist -m pytest ./tests/test_file.py
```

which would get me the result: 
``` 
specialist: No quickened code found in pytest! Try modifying it to run longer, or use the --targets option to analyze different source files.
```

what wasn't clear was the `--targets` meant the source code I wanted to see was quickened. I think I was assuming it would automatically know which classes I meant (how would it??). It wasn't until I figured out the following syntax that I started getting incredibly helpful results! 

``` shell
specialist --targets ./module/class_the_test_exercises.py -m pytest ./tests/test_file.py
```

**Comment by brandtbucher** [comment]
Thanks!

Yeah, I agree that the documentation surrounding this common case can probably be improved, possibly even with a short “Getting Started” section near the top.

It might even be possible to “magically” suggest what the user meant by seeing if we’ve loaded any files from outside of `site-packages` during the run. It probably wouldn’t be too hard to do something like:

```
specialist: No quickened code found in pytest! Try modifying it to run longer, or use the --targets option to analyze different source files.
specialist: Did you mean to add "--targets module/class_the_test_exercises.py"?
```

**Comment by matroscoe** [comment]
After I had posted about how would it I realized you probably could try to guess but I think your suggestion of adding a consider adding is much better than making the assumption and picking the wrong targets and confusing the user.

**Comment by brandtbucher** [comment]
c5adafc3a3d60da8c7742832da480abe172db9bb adds this suggestion feature. When you have some time, try out the current `main` head and see if you like the way it works! If so, I can probably make a new release next week.

Here is an example using specialist to run its own tests:

```
$ python -m specialist -m pytest --quiet
.......................................................                                                                                             [100%]
55 passed in 0.78s
specialist: No quickened code found in pytest! Try modifying it to run longer, or use the --targets option to analyze different source files.
specialist: Did you mean --targets '**/*' -m pytest --quiet?
```

**Comment by matroscoe** [comment]
Hi @brandtbucher, works excellent thanks so much for putting that together!

**Comment by brandtbucher** [comment]
Awesome, thanks!

**Comment by brandtbucher** [comment]
Finally got around to updating the README with a `pytest` example!
