### ISSUE TITLE
Not all adaptive instructions are bad

### ISSUE THREAD

**Issue by nickdrozd** [brandtbucher/specialist#5]
This is a cool tool!

It looks like all the color coding is currently done in the ROYG range. Redder means less specialized, greener means more specialized.

But code can be unspecialized either because it wasn't run enough, or because it was run enough but had some other issue. The former case isn't very interesting, while the latter is potentially actionable.

So I suggest using red just for things that could be specialized but aren't, and BIV colors for things that aren't specialized for boring reasons (not run enough, implemented in C, etc). This will make it immediately clear where the problem areas are.

**Comment by brandtbucher** [comment]
Thanks!

There are sort of two categories of unspecialized adaptive instructions:
- Ones which were quickened, but are going to try specializing the next time they're hit. These are mostly "boring", as you say.
- Ones which are currently "backing off" from a prior failed specialization attempt. These are mostly "interesting".

While we don't have a way of knowing *why* a specialization attempt failed, we are still able to tell these two cases apart *reasonably* well. I agree that it would be helpful to visually represent the differences between these two cases (which are currently both just red).

However, I'm not sure that more colors is the right solution... I'm worried it would just clutter up and complicate the output, especially when considering the blending of colors from many bytecode instructions (not to mention `--blue` mode and general accessibility concerns).

Instead, I think a good way to handle this is just to treat the first category ("about-to-specialize") the same as "unquickened", and don't give them any color at all. They're not actually slowing anything down, and may even represent dead code. Further, they're not *too* difficult to detect: just peek into the next `CACHE` entry (the backoff counter) and see if it's zero.

Thoughts?

**Comment by nickdrozd** [comment]
I'm approaching this tool as a kind of profiler, in the sense that it can highlight places where performance can be meaningfully improved. To that end (and of course, this is just one possible use case), I would like to look at the generated report and easily pick out the places that need a closer look. I don't really care about the stuff that isn't subject to specialization for whatever reason. It can be displayed in a different color, not colored at all, or something else, just so long as the problem areas can be distinguished easily.

**Comment by brandtbucher** [comment]
2eff16c75885afe33cf2087b0da00a00d4a66480 treats all about-to-adapt instructions (corresponding to "boring" stuff like dead code) as unquickened, which keeps them from being colored red in the output (the screenshots and examples in the README still need updating).

When you have some time, try out the current `main` head and see if you like the way it looks! If so, I can probably make a new release next week.

**Comment by nickdrozd** [comment]
There seems to be less red, and much of the difference is in places that I think shouldn't be red. So AFAICT, the change works!

**Comment by brandtbucher** [comment]
Awesome, thanks for trying it out!

**Comment by brandtbucher** [comment]
Finally got around to updating the README!
